import type { Metadata } from "next";
import {  Mulish } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ['cyrillic'],
})

export const metadata: Metadata = {
  title: "Adidas",
  description: "Generated by create Pietra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${mulish.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
